name: app
type: java:17
disk: 2048

build:
  hooks:
    build: |
      ./gradlew build --no-daemon

web:
  commands:
    start: java -jar build/libs/YOUR_APP_NAME.jar  # Replace with your JAR filename

mounts:
  "/data":
    source: local
