name: app
type: java:17
disk: 2048

web:
  commands:
    start: java -Dserver.port=8080 -jar build/libs/Stirling-PDF-0.45.6.jar
    # Pre-built JAR must exist in repo

mounts:
  "/data":
    source: local
